name: backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
    paths:
      - "apps/backend/**"
      - "packages/db/**"
      - ".github/workflows/backend-ci.yml"
      - "package.json"

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'area:backend') || contains(github.event.pull_request.labels.*.name, 'backend:enhancement') || contains(github.event.pull_request.labels.*.name, 'area-backend') }}

    steps:
      - name: 'ğŸ™ï¸ Check out code'
        uses: actions/checkout@v3

      - name: 'ğŸ’½ï¸  Init'
        id: backend-init
        uses: Chia1104/chia-stack/.github/actions/init-pnpm@main

      - name: 'ğŸ“¦  Install'
        id: backend-install
        uses: Chia1104/chia-stack/.github/actions/pnpm-install@main
        with:
          INSTALL_COMMAND: '--filter db --filter tsconfig --filter root'

      - name: 'ğŸš¨ï¸  ESLint, Type checking, Unit tests'
        id: backend-lint-test
        uses: Chia1104/chia-stack/.github/actions/lint-test@main
        with:
          COMMAND: '--filter backend...'
          TURBO_TEAM: ${{ env.TURBO_TEAM }}
          TURBO_TOKEN: ${{ env.TURBO_TOKEN }}
